#!/usr/bin/env bash
# This script is displaying the time for 12 hours and 59 minutes number
# displays hours from 0 to 12
# displays minutes from 1 to 59

var="Hour"
h="0"
while [ $h -lt 13 ]; do
  echo "$var:" "$h"
  s="1"
 while [ $s -lt 60 ]; do	
	 echo "$s"
	 ((s++))
		
 ((i++))
done
